[package]
name = "parquet-rs-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "51.0.0"
clap = "4.5.4"
parquet = "51.0.0"
