[package]
name = "format-study"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "51.0.0"
bytes = "1.6.0"
parquet = { git = "https://github.com/XiangpengHao/arrow-rs.git", branch = "metadata-bench"}
rand = "0.8.5"
thrift = "0.17.0"

[dev-dependencies]
criterion = "0.5.1"


[[bench]]
name = "metadata"
harness = false
