name: Docker Build and Run Benchmark

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Benchmark
        run: |
          docker build -t parquet-gym . 
          docker run -v ${{ github.workspace }}/results:/app/results parquet-gym

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: results/
